lat-dataset-path: ./energy_dataset/wmt14ende_gpu_1080.csv
feature-norm: [640, 6, 2048, 6, 640, 6, 2048, 6, 6, 2]
lat-norm: 200
feature-dim: 10
hidden-dim: 400
hidden-layer-num: 3
ckpt-path: ./energy_dataset/predictors/wmt14ende_gpu_1080.pt
train-steps: 5000
bsz: 128
lr: 1e-5
